/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Unidad4;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author ALUMNO_07
 */
public class Frame_Auto extends javax.swing.JFrame {

    /**
     * Creates new form Frame_Auto
     */
    ButtonGroup grupot;
    Conexion c;
    VentaAutos va;
    ConsultaAuto a;
    Frame_Auto ra;
    public Frame_Auto() {
        initComponents();
        
        for(int i=2000;i<=2022;i++){
            cmbanio.addItem(""+i);
        }
        grupot=new ButtonGroup();
        grupot.add(rbestandar);
        grupot.add(rbautomatico);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbltitulo = new javax.swing.JLabel();
        lblmarca = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbmarca = new javax.swing.JComboBox<>();
        txtmodelo = new javax.swing.JTextField();
        cmbcolor = new javax.swing.JComboBox<>();
        cmbanio = new javax.swing.JComboBox<>();
        txtpreciobase = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rbestandar = new javax.swing.JRadioButton();
        rbautomatico = new javax.swing.JRadioButton();
        btnregistrar = new javax.swing.JButton();
        btnmostrar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnvender = new javax.swing.JButton();
        cmbcliente = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        mnautos = new javax.swing.JMenu();
        mnrauto = new javax.swing.JMenuItem();
        mncauto = new javax.swing.JMenuItem();
        mnclientes = new javax.swing.JMenu();
        mnrclientes = new javax.swing.JMenuItem();
        mnccliente = new javax.swing.JMenuItem();
        mnventas = new javax.swing.JMenu();
        mncventa = new javax.swing.JMenuItem();
        mncventas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 500));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 500));
        jPanel1.setLayout(null);

        lbltitulo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbltitulo.setForeground(new java.awt.Color(0, 153, 51));
        lbltitulo.setText("Registro Auto");
        jPanel1.add(lbltitulo);
        lbltitulo.setBounds(130, 50, 109, 22);

        lblmarca.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblmarca.setForeground(new java.awt.Color(255, 255, 255));
        lblmarca.setText("Marca");
        jPanel1.add(lblmarca);
        lblmarca.setBounds(53, 134, 43, 19);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Modelo");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(53, 177, 53, 19);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Color");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(53, 220, 38, 19);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Año");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(53, 264, 27, 19);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Precio Base");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(53, 309, 84, 19);

        cmbmarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar...", "VW", "FORD", "NISSAN", "SUBARU", "AUDI", "DODGE" }));
        jPanel1.add(cmbmarca);
        cmbmarca.setBounds(147, 131, 107, 26);
        jPanel1.add(txtmodelo);
        txtmodelo.setBounds(147, 175, 107, 24);

        cmbcolor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar...", "ROJO", "NEGRO", "AZUL", "GRIS", "VERDE", "BLANCO" }));
        jPanel1.add(cmbcolor);
        cmbcolor.setBounds(147, 217, 107, 26);

        cmbanio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar..." }));
        jPanel1.add(cmbanio);
        cmbanio.setBounds(147, 261, 107, 26);
        jPanel1.add(txtpreciobase);
        txtpreciobase.setBounds(147, 307, 107, 24);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Transmición");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(53, 352, 85, 19);

        rbestandar.setBackground(new java.awt.Color(102, 255, 204));
        rbestandar.setText("Estandar");
        rbestandar.setOpaque(false);
        jPanel1.add(rbestandar);
        rbestandar.setBounds(147, 348, 83, 28);

        rbautomatico.setBackground(new java.awt.Color(102, 255, 204));
        rbautomatico.setText("Automatico");
        rbautomatico.setOpaque(false);
        jPanel1.add(rbautomatico);
        rbautomatico.setBounds(272, 348, 97, 28);

        btnregistrar.setText("Mostrar");
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnregistrar);
        btnregistrar.setBounds(161, 401, 75, 32);

        btnmostrar.setText("Registrar");
        btnmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmostrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnmostrar);
        btnmostrar.setBounds(43, 401, 77, 32);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Unidad4/logo.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(280, 70, 60, 40);

        btnvender.setText("Vender\n");
        btnvender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvenderActionPerformed(evt);
            }
        });
        jPanel1.add(btnvender);
        btnvender.setBounds(272, 23, 71, 32);

        cmbcliente.setText("Cliente");
        cmbcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbclienteActionPerformed(evt);
            }
        });
        jPanel1.add(cmbcliente);
        cmbcliente.setBounds(278, 401, 69, 32);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 380, 450);

        mnautos.setText("Autos");

        mnrauto.setText("Registro");
        mnautos.add(mnrauto);

        mncauto.setText("Consulta");
        mnautos.add(mncauto);

        jMenuBar2.add(mnautos);

        mnclientes.setText("Clientes");

        mnrclientes.setText("Registro");
        mnclientes.add(mnrclientes);

        mnccliente.setText("Consulta");
        mnclientes.add(mnccliente);

        jMenuBar2.add(mnclientes);

        mnventas.setText("Ventas");

        mncventa.setText("Registro");
        mnventas.add(mncventa);

        mncventas.setText("Consultas");
        mnventas.add(mncventas);

        jMenuBar2.add(mnventas);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmostrarActionPerformed
        String trans="";
        c=new Conexion();
        if(rbestandar.isSelected()){
            trans="Estandar";
        }else{
            if(rbautomatico.isSelected()){
                trans="Automatico";
            }
        }
        String sql="insert into auto (marca,modelo,color,anio,precio,transmicion)"
                +"values('"+cmbmarca.getSelectedItem().toString()+"','"+txtmodelo.getText()+"','"+cmbcolor.getSelectedItem().toString()
                +"',"+cmbanio.getSelectedItem().toString()+","+txtpreciobase.getText()+",'"+trans+"')";
        try{
            System.err.println(sql);
            c.proceso_tabla(sql);
            JOptionPane.showMessageDialog(null, "Registro exitoso");
        }
        catch(Exception e){
            System.out.println("Error en la inserción"+e.getMessage());
        }
        finally{
            c.cerrar_con();
        }
        JOptionPane.showMessageDialog(null,"Se insertaron los datos");
    }//GEN-LAST:event_btnmostrarActionPerformed

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed
        // TODO add your handling code here:
        a = new ConsultaAuto(); 
    }//GEN-LAST:event_btnregistrarActionPerformed

    private void btnvenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvenderActionPerformed
        VentaAutos a = new VentaAutos();
        this.jPanel1.setVisible(false);
        add(a);
        a.setVisible(true);
        repaint();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnvenderActionPerformed

    private void cmbclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbclienteActionPerformed
        RegistroCliente r = new RegistroCliente();
        this.jPanel1.setVisible(false);
        add(r);
        r.setVisible(true);
        repaint();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbclienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Auto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Auto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Auto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Auto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Auto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnmostrar;
    private javax.swing.JButton btnregistrar;
    private javax.swing.JButton btnvender;
    private javax.swing.JComboBox<String> cmbanio;
    private javax.swing.JButton cmbcliente;
    private javax.swing.JComboBox<String> cmbcolor;
    private javax.swing.JComboBox<String> cmbmarca;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblmarca;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JMenu mnautos;
    private javax.swing.JMenuItem mncauto;
    private javax.swing.JMenuItem mnccliente;
    private javax.swing.JMenu mnclientes;
    private javax.swing.JMenuItem mncventa;
    private javax.swing.JMenuItem mncventas;
    private javax.swing.JMenuItem mnrauto;
    private javax.swing.JMenuItem mnrclientes;
    private javax.swing.JMenu mnventas;
    private javax.swing.JRadioButton rbautomatico;
    private javax.swing.JRadioButton rbestandar;
    private javax.swing.JTextField txtmodelo;
    private javax.swing.JTextField txtpreciobase;
    // End of variables declaration//GEN-END:variables
}
