/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Unidad4;

import java.sql.ResultSet;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author LOUID
 */
public class RegistroCliente extends javax.swing.JPanel {

    /**
     * Creates new form RegistroCliente
     */
     ButtonGroup gruposexo;
     Conexion c;
     ConsultaCliente a;
     
    public RegistroCliente() {
        initComponents();
        setSize(400,500);
        setVisible(true);
        
        for(int i=18; i<71; i++)
        {
            cmbedad.addItem(""+i);
        }
        
        gruposexo=new ButtonGroup();
        gruposexo.add(rdhombre);
        gruposexo.add(rdmujer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnregistrar = new javax.swing.JButton();
        btnconsultar = new javax.swing.JButton();
        txtnombre = new javax.swing.JTextField();
        txtam = new javax.swing.JTextField();
        txtap = new javax.swing.JTextField();
        cmbedad = new javax.swing.JComboBox<>();
        txttelefono = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        rdhombre = new javax.swing.JRadioButton();
        rdmujer = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(255, 51, 51));
        setForeground(new java.awt.Color(255, 51, 51));
        setPreferredSize(new java.awt.Dimension(400, 500));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRO CLIENTES");
        add(jLabel1);
        jLabel1.setBounds(137, 26, 143, 19);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");
        add(jLabel2);
        jLabel2.setBounds(37, 75, 100, 19);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ap. Paterno");
        add(jLabel3);
        jLabel3.setBounds(40, 110, 100, 19);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ap. Materno");
        add(jLabel4);
        jLabel4.setBounds(40, 140, 100, 19);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Edad");
        add(jLabel5);
        jLabel5.setBounds(40, 170, 100, 19);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Genero");
        add(jLabel6);
        jLabel6.setBounds(40, 200, 100, 19);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Telefono");
        add(jLabel7);
        jLabel7.setBounds(40, 260, 100, 16);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Direccion");
        add(jLabel8);
        jLabel8.setBounds(40, 230, 100, 16);

        btnregistrar.setText("Registrar");
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });
        add(btnregistrar);
        btnregistrar.setBounds(83, 300, 100, 32);

        btnconsultar.setText("Consultar");
        btnconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarActionPerformed(evt);
            }
        });
        add(btnconsultar);
        btnconsultar.setBounds(217, 300, 100, 32);
        add(txtnombre);
        txtnombre.setBounds(170, 70, 130, 24);
        add(txtam);
        txtam.setBounds(170, 140, 130, 24);
        add(txtap);
        txtap.setBounds(170, 110, 130, 24);

        cmbedad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona Edad" }));
        add(cmbedad);
        cmbedad.setBounds(170, 170, 130, 26);
        add(txttelefono);
        txttelefono.setBounds(170, 260, 140, 24);
        add(txtdireccion);
        txtdireccion.setBounds(170, 230, 140, 24);

        rdhombre.setText("Hombre");
        add(rdhombre);
        rdhombre.setBounds(170, 200, 90, 28);

        rdmujer.setText("Mujer");
        add(rdmujer);
        rdmujer.setBounds(280, 200, 64, 28);
    }// </editor-fold>//GEN-END:initComponents

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed
        // TODO add your handling code here:
        String sexo="";
        c=new Conexion();
        if(rdhombre.isSelected()){
            sexo="Hombre";
        }else{
            if(rdmujer.isSelected()){
                sexo="Automatico";
            }
        }
        String sql="insert into clientes (nombre,ap_paterno,ap_materno,edad,genero,direccion,telefono)"
                +"values('"+txtnombre.getText()+"','"
                +txtap.getText()+"','"
                +txtam.getText()+"','"
                +cmbedad.getSelectedItem()+"','"
                +sexo+"','"
                +txtdireccion.getText()+"','"
                +txttelefono.getText().toString()+"')";
        try{
            System.err.println(sql);
            c.proceso_tabla(sql);
            JOptionPane.showMessageDialog(null, "Registro exitoso");
        }
        catch(Exception e){
            System.out.println("Error en la inserción"+e.getMessage());
        }
        finally{
            c.cerrar_con();
        }
        JOptionPane.showMessageDialog(null,"Se insertaron los datos");
        
        
    }//GEN-LAST:event_btnregistrarActionPerformed

    private void btnconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarActionPerformed
        
        a=new  ConsultaCliente();
    // TODO add your handling code here:
    }//GEN-LAST:event_btnconsultarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconsultar;
    private javax.swing.JButton btnregistrar;
    private javax.swing.JComboBox<String> cmbedad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton rdhombre;
    private javax.swing.JRadioButton rdmujer;
    private javax.swing.JTextField txtam;
    private javax.swing.JTextField txtap;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
