////Ventaja Reutilizacion en diferentes areas de trabajo(diferentes ventanas)
package Unidad4;

/**
 *
 * @author LOUID
 */
import java.sql.*;
import javax.swing.*;
public class VentaAutos extends javax.swing.JPanel {

    /**
     * Creates new form VentaAutos
     */
    
     Conexion c,a;
     ResultSet res, res1;
     
     String id_marca[]= new String[100];  //comantar
     //int cont = 1;
     
    public VentaAutos() 
    {
        initComponents();
        setSize(400,500);
        setVisible(true);
        try
        {
            c=new Conexion();
            res=c.consultar("select marca from auto");
            //res=c.consultar("select id_auto,marca from auto");   //jalar ID
            while(res.next())
            {
                //id_marca[cont]=res.getString("id_auto");  ///guardando id delas marcas  ///Jalar ID
                //cmbmarca.addItem(id_marca[cont]+res.getString("Marca"));   //Jalar ID
                cmbmarca.addItem(res.getString("Marca"));
                
            }
        }
        catch(Exception e)
        {
             System.out.println("error combos marca:"+e.getMessage());
        }
        try
        {
            a=new Conexion();
            res1=a.consultar("select nombre from clientes");
            //res=c.consultar("select id_auto,marca from auto");   //jalar ID
            while(res1.next())
            {
                //id_marca[cont]=res.getString("id_auto");  ///guardando id delas marcas  ///Jalar ID
                //cmbmarca.addItem(id_marca[cont]+res.getString("Marca"));   //Jalar ID
                cmbcliente.addItem(res1.getString("Nombre"));
                
            }
        }
        catch(Exception e)
        {
             System.out.println("error combos marca:"+e.getMessage());
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbmarca = new javax.swing.JComboBox<>();
        cmbmodelo = new javax.swing.JComboBox<>();
        chbasico = new javax.swing.JCheckBox();
        chintermedio = new javax.swing.JCheckBox();
        rbefectivo = new javax.swing.JRadioButton();
        rbtarjeta = new javax.swing.JRadioButton();
        btnvender = new javax.swing.JButton();
        btnconsultar = new javax.swing.JButton();
        btnregresar = new javax.swing.JButton();
        champlia = new javax.swing.JCheckBox();
        txtprecio = new javax.swing.JTextField();
        txtfecha = new javax.swing.JTextField();
        cmbcliente = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 51, 51));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(400, 500));
        setLayout(null);

        lbltitulo.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        lbltitulo.setForeground(new java.awt.Color(255, 255, 255));
        lbltitulo.setText("VENTA DE AUTOS ");
        add(lbltitulo);
        lbltitulo.setBounds(70, 30, 110, 17);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cliente ");
        add(jLabel2);
        jLabel2.setBounds(70, 110, 90, 19);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Marca");
        add(jLabel3);
        jLabel3.setBounds(70, 140, 70, 19);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Modelo");
        add(jLabel4);
        jLabel4.setBounds(70, 170, 70, 19);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Precio");
        add(jLabel5);
        jLabel5.setBounds(70, 210, 70, 19);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fecha");
        add(jLabel6);
        jLabel6.setBounds(70, 240, 70, 19);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Modo de Pago");
        add(jLabel7);
        jLabel7.setBounds(70, 270, 110, 19);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Seguro");
        add(jLabel8);
        jLabel8.setBounds(70, 300, 70, 19);

        cmbmarca.setBackground(new java.awt.Color(255, 255, 255));
        cmbmarca.setForeground(new java.awt.Color(0, 0, 0));
        cmbmarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige Marca" }));
        cmbmarca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbmarcaItemStateChanged(evt);
            }
        });
        add(cmbmarca);
        cmbmarca.setBounds(190, 130, 110, 26);

        cmbmodelo.setBackground(new java.awt.Color(255, 255, 255));
        cmbmodelo.setForeground(new java.awt.Color(0, 0, 0));
        cmbmodelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige Modelo" }));
        add(cmbmodelo);
        cmbmodelo.setBounds(190, 170, 110, 26);

        chbasico.setBackground(new java.awt.Color(255, 51, 51));
        chbasico.setForeground(new java.awt.Color(255, 255, 255));
        chbasico.setText("Basico");
        add(chbasico);
        chbasico.setBounds(180, 300, 70, 24);

        chintermedio.setBackground(new java.awt.Color(255, 51, 51));
        chintermedio.setForeground(new java.awt.Color(255, 255, 255));
        chintermedio.setText("Intermedio");
        add(chintermedio);
        chintermedio.setBounds(260, 300, 89, 24);

        rbefectivo.setBackground(new java.awt.Color(255, 51, 51));
        rbefectivo.setForeground(new java.awt.Color(255, 255, 255));
        rbefectivo.setText("Efectivo");
        add(rbefectivo);
        rbefectivo.setBounds(180, 270, 77, 28);

        rbtarjeta.setBackground(new java.awt.Color(255, 51, 51));
        rbtarjeta.setForeground(new java.awt.Color(255, 255, 255));
        rbtarjeta.setText("Tarjeta");
        add(rbtarjeta);
        rbtarjeta.setBounds(260, 270, 111, 28);

        btnvender.setBackground(new java.awt.Color(255, 51, 51));
        btnvender.setText("Vender");
        btnvender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvenderActionPerformed(evt);
            }
        });
        add(btnvender);
        btnvender.setBounds(90, 380, 71, 32);

        btnconsultar.setBackground(new java.awt.Color(255, 51, 51));
        btnconsultar.setText("Consultar");
        add(btnconsultar);
        btnconsultar.setBounds(207, 380, 90, 32);

        btnregresar.setBackground(new java.awt.Color(255, 51, 51));
        btnregresar.setText("Regresar");
        add(btnregresar);
        btnregresar.setBounds(260, 20, 90, 32);

        champlia.setBackground(new java.awt.Color(255, 51, 51));
        champlia.setForeground(new java.awt.Color(255, 255, 255));
        champlia.setText("Cobertura Amplia");
        add(champlia);
        champlia.setBounds(180, 330, 140, 24);

        txtprecio.setBackground(new java.awt.Color(255, 255, 255));
        txtprecio.setForeground(new java.awt.Color(0, 0, 0));
        add(txtprecio);
        txtprecio.setBounds(190, 200, 110, 24);

        txtfecha.setBackground(new java.awt.Color(255, 255, 255));
        txtfecha.setForeground(new java.awt.Color(0, 0, 0));
        add(txtfecha);
        txtfecha.setBounds(190, 230, 110, 24);

        cmbcliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona Cliente" }));
        add(cmbcliente);
        cmbcliente.setBounds(190, 100, 140, 26);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbmarcaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbmarcaItemStateChanged
        res=null;
        this.remove(cmbmodelo);
        cmbmodelo = new JComboBox();
        cmbmodelo.setBounds(190, 170, 110, 26);
        try
        {
            cmbmodelo.addItem("Elige Modelo");
            c=new Conexion();
            res=c.consultar("select modelo from auto where marca= '"+cmbmarca.getSelectedItem().toString()+"'");
            while(res.next())
            {
                cmbmodelo.addItem(res.getString("Modelo"));
            }
            
        }
        catch(Exception ev)
        {
            System.out.println("error itemState"+ev.getMessage());
        }
        finally {c.cerrar_con();}
        
        add(cmbmodelo);
        repaint();
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbmarcaItemStateChanged

    private void btnvenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvenderActionPerformed

        try
        {
            c=new Conexion();
            c.proceso_tabla("insert into ventaautos"
                    +"values ("+cmbcliente.getSelectedItem()+
                    //",'"+id_marca[(cmbmarca.getSelectedIndex()+1)]+"'")");
        }
        catch(Exception e)
        {
        
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnvenderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconsultar;
    private javax.swing.JButton btnregresar;
    private javax.swing.JButton btnvender;
    private javax.swing.JCheckBox champlia;
    private javax.swing.JCheckBox chbasico;
    private javax.swing.JCheckBox chintermedio;
    private javax.swing.JComboBox<String> cmbcliente;
    private javax.swing.JComboBox<String> cmbmarca;
    private javax.swing.JComboBox<String> cmbmodelo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JRadioButton rbefectivo;
    private javax.swing.JRadioButton rbtarjeta;
    private javax.swing.JTextField txtfecha;
    private javax.swing.JTextField txtprecio;
    // End of variables declaration//GEN-END:variables
}
